### PR TITLE
Fix deprecation of TEMP_CELSIUS

### LINKED ISSUE #55: Integration fails to load afrer upgrading to Home Assistant 2023.1.0
Upgraded to Home Assistant 2023.1.0 this morning and the integration fails to load. There are two distinct errors in the logs;

image

Both have the same error text;

`Logger: homeassistant.setup
Source: setup.py:340
First occurred: 08:49:19 (4 occurrences)
Last logged: 08:49:29

Unable to prepare setup for platform ramses_cc.sensor: Platform not found (cannot import name 'TEMP_CELSIUS' from 'homeassistant.components.sensor' (/usr/src/homeassistant/homeassistant/components/sensor/__init__.py)).
Unable to prepare setup for platform ramses_cc.climate: Platform not found (cannot import name 'TEMP_CELSIUS' from 'homeassistant.components.climate' (/usr/src/homeassistant/homeassistant/components/climate/__init__.py)).`

### PR DESCRIPTION
**Pull request by DJBenson**
I made these changes to my local package and it resolved #55. Hoping this covers the entire fix.

### CODE REVIEW

**Comment by mazzy89** [comment]
not needed. the fix has been already implemented https://github.com/zxdavb/ramses_cc/commit/8f99381d6d1e3a77cf6a9b046d63701dd2b471a5

**Comment by DJBenson** [comment]
> not needed. the fix has been already implemented https://github.com/zxdavb/ramses_cc/commit/8f99381d6d1e3a77cf6a9b046d63701dd2b471a5

Which has completely broken my install.

**Comment by mazzy89** [comment]
yeah same here https://github.com/zxdavb/ramses_cc/issues/57 😂 unfortunately there is not much tests coverage so we are the guinea pigs 😎

**Comment by DJBenson** [comment]
That's the fun with free/open source software 😄

**Comment by mazzy89** [comment]
yeah indeed.

**Comment by DJBenson** [comment]
Closing as resolved by the developer.

**Comment by zxdavb** [comment]
Thanks for your efforts - sorry I couldn't merge your PR as was.

**Pull request closed without merging**
