### PR TITLE
Fix for volume flow rate

### PR DESCRIPTION
**Pull request by janvkem**
Added VOLUME_FLOW_RATE_LITERS_PER_SECOND

### CODE REVIEW

**Comment by zxdavb** [comment]
Is it L/s for both Itho _and_ Orcon?

**Comment by janvkem** [comment]
Orcon is L/s in 31DA

**Comment by Kars-de-Jong** [comment]
What needs to be done to get this PR merged? (I also have an Orcon fan, which now incorrectly shows the flow rate as a percentage).

**Comment by janvkem** [comment]
I have it running without errors (added manually)

**Pull request merged**
